### ISSUE TITLE
socket.error: [Errno 22] Invalid argument

### ISSUE THREAD

**Issue by putro** [crooks/aam2mail#1]
sometimes aam2mail stops working, here's the traceback:
Traceback (most recent call last):
  File "/usr/local/bin/aam2mail", line 408, in <module>
    daemon.run()
  File "/usr/local/bin/aam2mail", line 35, in run
    aam.main()
  File "/usr/local/bin/aam2mail", line 337, in main
    self.news = nntplib.NNTP(server, readermode=True)
  File "/usr/lib/python2.7/nntplib.py", line 125, in **init**
    self.welcome = self.shortcmd('mode reader')
  File "/usr/lib/python2.7/nntplib.py", line 259, in shortcmd
    return self.getresp()
  File "/usr/lib/python2.7/nntplib.py", line 214, in getresp
    resp = self.getline()
  File "/usr/lib/python2.7/nntplib.py", line 203, in getline
    line = self.file.readline()
  File "/usr/lib/python2.7/socket.py", line 447, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 22] Invalid argument

for what I understand it's a socket (so communication related ?) error, but I've not
problem with connection. If I restart it, it has no problem. 
Nothing is logged (I see the traceback in console).

**Comment by crooks** [comment]
Hi,

Thanks for the report.
I've added a trap for socket.error exceptions.  Please can you try it out and let me know if it fixes your problem?

Steve
